### ISSUE TITLE
add support for unsinged value

### ISSUE THREAD

**Issue by iFwu** [unscrambl/json-long#2]
I see your code use Long.fromString, but not assigned if the long number is unsigned type.
I think an option can be provided to indicate that the json contain a unsigned long type

**Comment by mustafa-cosar** [comment]
Hi @iFwu, thank you for your interest in json-long.

I checked and `Long.fromString` does take an `unsigned` argument.

If I understand correctly, you want to use `json-long` like so:
```js
JSONLong.parse(jsonString, {unsigned: true})
```

**Comment by iFwu** [comment]
That's it

发自我的 iPhone

在 2019年1月15日，下午10:59，Mustafa Şenol Coşar <notifications@github.com<mailto:notifications@github.com>> 写道：


Hi @iFwu<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FiFwu&data=02%7C01%7C%7Cc62698171ab54f195f8a08d67afa0ed8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636831611742540006&sdata=j9baMrVrzKPRGEK%2FArBsSN6F0wlxkL3li5%2FVOFkdv30%3D&reserved=0>, thank you for your interest in json-long.

I checked and Long.fromString does take an unsigned argument.

If I understand correctly, you want to use json-long like so:

JSONLong.parse(jsonString, {unsigned: true})

**Comment by mohyt** [comment]
issue resolved
